import { useTranslation } from "react-i18next";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";
import SEOHead from "@/components/SEOHead";

export default function LimitedLiability() {
    const { t } = useTranslation();

    return (
        <div className="min-h-screen bg-background text-foreground">
            <SEOHead
                title="Limited Liability Policy - BTP xID by TerraBT | SAP BTP Access & Credential Management"
                description="Limited Liability Disclaimer for the TerraBT website, BTP xID desktop app, BTP xID Web, and subscription services."
                path="/limited-liability"
            />
            <Navigation />

            <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 md:py-20">
                <h1 className="text-3xl md:text-4xl font-bold mb-8">Limited Liability Disclaimer</h1>
                <p className="text-muted-foreground mb-8">Last Updated: June 18, 2026</p>

                <div className="space-y-8 prose prose-gray dark:prose-invert max-w-none">
                    <section>
                        <h2 className="text-2xl font-semibold mb-4">1. General Disclaimer</h2>
                        <p>
                            The information provided on the TerraBT website and within BTP xID products is for general informational and administrative purposes only. All information is provided in good faith; however, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information on the Site or generated by the BTP xID software.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold mb-4">2. Professional Advice and Access Management Disclaimer</h2>
                        <p>
                            BTP xID is a tool that surfaces information already present in your SAP BTP environment and helps you perform administrative actions (viewing users, managing role collections, creating/rotating/deleting service keys and API credentials). It is <strong>not</strong> a substitute for proper security governance, access reviews, or professional advice.
                        </p>
                        <p className="mt-2">
                            The software does not automatically secure your landscape. You remain fully responsible for:
                        </p>
                        <ul className="list-disc pl-6 space-y-1 mt-2">
                            <li>Reviewing and acting on the information the app displays</li>
                            <li>Correctly identifying and revoking unnecessary access</li>
                            <li>Configuring appropriate role collections and scopes</li>
                            <li>Rotating and protecting credentials</li>
                            <li>Complying with your organization's security policies and regulatory requirements</li>
                        </ul>
                        <p className="mt-2">
                            Before taking any actions based upon data shown in BTP xID, we strongly encourage you to validate findings and consult with appropriate security, compliance, and SAP BTP professionals within your organization.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold mb-4">3. Limitation of Liability</h2>
                        <p>
                            To the maximum extent permitted by applicable law, in no event shall TerraBT, its affiliates, agents, directors, employees, suppliers, or licensors be liable for any indirect, punitive, incidental, special, consequential, or exemplary damages, including without limitation damages for loss of profits, goodwill, use, data, or other intangible losses, arising out of or relating to:
                        </p>
                        <ul className="list-disc pl-6 space-y-1 mt-2">
                            <li>The use of, or inability to use, the TerraBT website or BTP xID software</li>
                            <li>Any decisions or actions you take (or fail to take) based on information displayed by BTP xID</li>
                            <li>Security incidents, unauthorized access, credential leakage, or over-privileged accounts in your SAP BTP landscape</li>
                            <li>Any data loss or corruption on your local device</li>
                        </ul>
                        <p className="mt-2">
                            BTP xID is provided as an administrative visibility and management aid. You acknowledge that effective security depends on how you interpret and act on the data the software makes visible. TerraBT is not responsible for the security posture of your SAP BTP environments.
                        </p>
                        <p className="mt-2">
                            Under no circumstances will TerraBT be responsible for any damage, loss, or injury resulting from hacking, tampering, or other unauthorized access or use of the service or your account or the information contained therein.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold mb-4">4. Technology and Third-Party Platform Disclaimer</h2>
                        <p>
                            SAP and SAP Business Technology Platform are trademarks or registered trademarks of SAP SE or its affiliates in Germany and in several other countries. TerraBT is an independent company and is not affiliated with, endorsed by, or sponsored by SAP SE.
                        </p>
                        <p className="mt-2">
                            BTP xID interacts with SAP BTP exclusively via official, publicly documented SAP APIs and authentication mechanisms. TerraBT makes no warranty that SAP will continue to support any particular API or that changes by SAP will not affect the functionality of BTP xID.
                        </p>
                        <p className="mt-2">
                            Any mention of third-party trademarks is for identification and reference regarding compatibility and expertise only.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold mb-4">5. Contact Us</h2>
                        <p>
                            If you have any questions about this Limited Liability Disclaimer, please contact us at:
                        </p>
                        <div className="mt-4 p-4 bg-muted/30 rounded-lg">
                            <p className="mt-2">Email: <a href="mailto:support@terrabt.com" className="text-primary hover:underline">support@terrabt.com</a></p>
                        </div>
                    </section>
                </div>
            </main>
            <Footer />
        </div>
    );
}
